# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/R&D/UHDIris/scripts/irisToolUi.ui'
#
# Created: Thu Sep 12 16:40:24 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_irisToolUi(object):
    def setupUi(self, irisToolUi):
        irisToolUi.setObjectName("irisToolUi")
        irisToolUi.resize(517, 139)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(irisToolUi.sizePolicy().hasHeightForWidth())
        irisToolUi.setSizePolicy(sizePolicy)
        irisToolUi.setMaximumSize(QtCore.QSize(16777215, 139))
        self.gridLayout = QtWidgets.QGridLayout(irisToolUi)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(irisToolUi)
        self.label.setObjectName("label")
        #self.horizontalLayout_2.addWidget(self.label)
        #self.renderEngine = QtWidgets.QComboBox(irisToolUi)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.renderEngine.sizePolicy().hasHeightForWidth())
        #self.renderEngine.setSizePolicy(sizePolicy)
        #self.renderEngine.setObjectName("renderEngine")
        #self.renderEngine.addItem("")
        #self.renderEngine.addItem("")
        #self.horizontalLayout_2.addWidget(self.renderEngine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(irisToolUi)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.irisFolder = QtWidgets.QPushButton(irisToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.irisFolder.sizePolicy().hasHeightForWidth())
        self.irisFolder.setSizePolicy(sizePolicy)
        self.irisFolder.setObjectName("irisFolder")
        self.horizontalLayout_4.addWidget(self.irisFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(irisToolUi)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(irisToolUi)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.loadLeft = QtWidgets.QRadioButton(irisToolUi)
        self.loadLeft.setObjectName("loadLeft")
        self.horizontalLayout_3.addWidget(self.loadLeft)
        #self.loadBoth = QtWidgets.QRadioButton(irisToolUi)
        #self.loadBoth.setObjectName("loadBoth")
        #self.horizontalLayout_3.addWidget(self.loadBoth)
        self.loadRight = QtWidgets.QRadioButton(irisToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadRight.sizePolicy().hasHeightForWidth())
        self.loadRight.setSizePolicy(sizePolicy)
        self.loadRight.setObjectName("loadRight")
        self.horizontalLayout_3.addWidget(self.loadRight)
        self.line_2 = QtWidgets.QFrame(irisToolUi)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(irisToolUi)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.colorPreset = QtWidgets.QComboBox(irisToolUi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorPreset.sizePolicy().hasHeightForWidth())
        self.colorPreset.setSizePolicy(sizePolicy)
        self.colorPreset.setObjectName("colorPreset")
        self.colorPreset.addItem("")
        self.colorPreset.addItem("")
        self.colorPreset.addItem("")
        self.horizontalLayout_3.addWidget(self.colorPreset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(irisToolUi)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.setup = QtWidgets.QPushButton(irisToolUi)
        self.setup.setObjectName("setup")
        self.verticalLayout_2.addWidget(self.setup)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(irisToolUi)
        QtCore.QMetaObject.connectSlotsByName(irisToolUi)

    def retranslateUi(self, irisToolUi):
        irisToolUi.setWindowTitle(QtWidgets.QApplication.translate("irisToolUi", "Texturing XYZ iris Tool", None, -1))
        #self.label.setText(QtWidgets.QApplication.translate("irisToolUi", "Render Engine............................................................................", None, -1))
        #self.renderEngine.setItemText(0, QtWidgets.QApplication.translate("irisToolUi", "Arnold", None, -1))
        #self.renderEngine.setItemText(1, QtWidgets.QApplication.translate("irisToolUi", "Vray(coming soon)", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("irisToolUi", "UHD Iris Folder :", None, -1))
        self.irisFolder.setText(QtWidgets.QApplication.translate("irisToolUi", "pick UHD Iris Folder", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("irisToolUi", "Side to load :", None, -1))
        self.loadLeft.setText(QtWidgets.QApplication.translate("irisToolUi", "left", None, -1))
        #self.loadBoth.setText(QtWidgets.QApplication.translate("irisToolUi", "both", None, -1))
        self.loadRight.setText(QtWidgets.QApplication.translate("irisToolUi", "right", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("irisToolUi", "Color Preset : .................", None, -1))
        self.colorPreset.setItemText(0, QtWidgets.QApplication.translate("irisToolUi", "Blue", None, -1))
        self.colorPreset.setItemText(1, QtWidgets.QApplication.translate("irisToolUi", "Brown", None, -1))
        self.colorPreset.setItemText(2, QtWidgets.QApplication.translate("irisToolUi", "Green", None, -1))
        self.setup.setText(QtWidgets.QApplication.translate("irisToolUi", "Setup", None, -1))

